name = "tillallhours"
type = "webpack"
# account_id = INSERT THE ACCT ID FOR CLOUDFLARE WORKERS ACCT

[env.staging]
workers_dev = true

[env.production]
routes = ["tillallhours.com/*","*.tillallhours.com/*"]
# zone_id = INSERT THE ZONE ID FOR CLOUDFLARE WORKERS ACCT

[site]
bucket = "./public"
entry-point = "workers-site"
